# Generated by Django 3.2.21 on 2023-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='image/default.webp', upload_to='avatars'),
        ),
    ]
